# Display.
title: "JavaScript versus Research Computing"
subtitle: "A Brief Guide for Those Who Regret That This Has Become Necessary"
author: "Greg Wilson"
copyrightyear: "2017"

# Code highlighting.
highlighter: rouge

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>
